// Runtime read of the bundled USDA fireshed snapshot. Validation runs once at
// module load; downstream code sees either { ok: true } or { ok: false }.
// This module NEVER hits apps.fs.usda.gov — the snapshot is generated by
// scripts/sync-fireshed.ts and committed to the repo.

// The snapshot files are imported as raw text so Vite doesn't need a custom
// loader for the `.geojson` extension. Both are produced by
// scripts/sync-fireshed.ts and committed to the repo.
import rawInventoryText from "./inventory.geojson?raw";
import rawProvenanceText from "./provenance.json?raw";
import {
  FireshedInventoryCollectionSchema,
  FireshedProvenanceSchema,
  type FireshedInventoryCollection,
  type FireshedProvenance,
} from "./schema";

export type FireshedInventoryLoad =
  | {
      ok: true;
      collection: FireshedInventoryCollection;
      provenance: FireshedProvenance;
    }
  | { ok: false; error: string; blockedUpstream?: BlockedUpstreamMeta };

export type BlockedUpstreamMeta = {
  reason: string;
  lastAttemptAt: string | null;
};

// Detect the SYNC_BLOCKED sentinel written by scripts/sync-fireshed.ts when
// the USDA MapServer refuses record retrieval. This surfaces a structured,
// truthful blocked-upstream state to the UI instead of a generic "invalid"
// schema error.
function detectBlockedUpstream(
  rawInventory: unknown,
  rawProvenance: unknown,
): BlockedUpstreamMeta | null {
  const inv =
    rawInventory && typeof rawInventory === "object"
      ? (rawInventory as Record<string, unknown>)
      : {};
  const prov =
    rawProvenance && typeof rawProvenance === "object"
      ? (rawProvenance as Record<string, unknown>)
      : {};
  const invStatus = typeof inv._status === "string" ? inv._status : null;
  const provStatus = typeof prov._status === "string" ? prov._status : null;
  if (invStatus?.startsWith("SYNC_BLOCKED") || provStatus?.startsWith("SYNC_BLOCKED")) {
    return {
      reason:
        typeof prov.reason === "string"
          ? prov.reason
          : "USDA MapServer/29 refused record retrieval at sync time.",
      lastAttemptAt:
        typeof prov.attemptedAt === "string" ? prov.attemptedAt : null,
    };
  }
  return null;
}

function loadOnce(): FireshedInventoryLoad {
  let inventoryRaw: unknown;
  let provenanceRaw: unknown;
  try {
    inventoryRaw = JSON.parse(rawInventoryText as unknown as string);
    provenanceRaw = JSON.parse(rawProvenanceText as unknown as string);
  } catch (err) {
    return {
      ok: false,
      error: `fireshed snapshot is not valid JSON: ${
        err instanceof Error ? err.message : String(err)
      }`,
    };
  }
  const blocked = detectBlockedUpstream(inventoryRaw, provenanceRaw);
  if (blocked) {
    return {
      ok: false,
      error: `fireshed snapshot is intentionally blocked upstream: ${blocked.reason}`,
      blockedUpstream: blocked,
    };
  }
  const inv = FireshedInventoryCollectionSchema.safeParse(inventoryRaw);
  if (!inv.success) {
    return {
      ok: false,
      error: `fireshed inventory failed validation: ${inv.error.message}`,
    };
  }
  const prov = FireshedProvenanceSchema.safeParse(provenanceRaw);
  if (!prov.success) {
    return {
      ok: false,
      error: `fireshed provenance failed validation: ${prov.error.message}`,
    };
  }
  if (prov.data.snapshot.featureCount !== inv.data.features.length) {
    return {
      ok: false,
      error: `provenance featureCount (${prov.data.snapshot.featureCount}) does not match inventory features (${inv.data.features.length})`,
    };
  }
  return { ok: true, collection: inv.data, provenance: prov.data };
}

export const fireshedInventory: FireshedInventoryLoad = loadOnce();
