/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IdahoRouteImport } from './routes/idaho'
import { Route as IndexRouteImport } from './routes/index'

const IdahoRoute = IdahoRouteImport.update({
  id: '/idaho',
  path: '/idaho',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/idaho': typeof IdahoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/idaho': typeof IdahoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/idaho': typeof IdahoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/idaho'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/idaho'
  id: '__root__' | '/' | '/idaho'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdahoRoute: typeof IdahoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/idaho': {
      id: '/idaho'
      path: '/idaho'
      fullPath: '/idaho'
      preLoaderRoute: typeof IdahoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdahoRoute: IdahoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
